# Must be unique in a given SonarQube instance
sonar.projectKey=node-lib


# This is the name and version displayed in the SonarQube UI.
# Was mandatory prior to SonarQube 6.1.
sonar.projectName=node-lib
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file.
sonar.sources=ia_map_lib/
sonar.tests = tests/

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

sonar.issue.ignore.multicriteria=e1,e2, e3, e4, e5, e6, e7
# python:S3776 : Cognitive Complexity of functions should not be too high
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S3776
sonar.issue.ignore.multicriteria.e1.resourceKey=src/node-lib/ia_map_lib/config/configurator.py

sonar.issue.ignore.multicriteria.e2.ruleKey=python:S3776
sonar.issue.ignore.multicriteria.e2.resourceKey=src/node-lib/ia_map_lib/sinks/kafkaSink.py

sonar.issue.ignore.multicriteria.e3.ruleKey=python:S3776
sonar.issue.ignore.multicriteria.e3.resourceKey=src/node-lib/ia_map_lib/sources/kafkaSource.py

sonar.issue.ignore.multicriteria.e4.ruleKey=python:S3776
sonar.issue.ignore.multicriteria.e4.resourceKey=src/node-lib/ia_map_lib/utils.py

sonar.issue.ignore.multicriteria.e5.ruleKey=python:S3776
sonar.issue.ignore.multicriteria.e5.resourceKey=src/node-lib/ia_map_lib/config/mapper.py

sonar.issue.ignore.multicriteria.e6.ruleKey=python:S3776
sonar.issue.ignore.multicriteria.e6.resourceKey=src/node-lib/tests/test_serdes.py

sonar.issue.ignore.multicriteria.e7.ruleKey=python:S3776
sonar.issue.ignore.multicriteria.e7.resourceKey=src/node-lib/tests/test_projector.py


