name: Sync with JIRA

on:
  workflow_dispatch: 
  issues: 
    types:
      - opened
      - edited
      - transferred
      - reopened

jobs:
  sync-to-jira:
    uses: NationalDigitalTwin/shared-workflows/.github/workflows/jira-sync.yml@main
    with:
      jira-url: https://ndtp.atlassian.net
      jira-project: TPT
      issue-mapping-file: .github/jira-mapping-rules.yml
    secrets: inherit

  